version: '3'

services:

  todoback:
    image: todobackend
    ports:
      - 3001:3001

  todofront:
    image: todofrontend
    environment:
      REACT_APP_API_HOST: todoback
    ports: 
      - 3000:3000
    depends_on:
      - todoback

  todotests:
    image: todotests
    environment: 
     FRONT_HOST: todofront
    depends_on: 
      - todoback
      - todofront